<template>
  <article>
      <h1>Loren ipsum</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a efficitur massa. Donec mi ipsum, volutpat lobortis dapibus nec, tempus sed ante. Integer ut lacinia dui, in egestas nibh. Nunc at elit massa. Etiam aliquet viverra metus at sodales. Nulla fermentum interdum elit ut fermentum. Morbi volutpat turpis nunc, eu facilisis nisl volutpat vel. Duis id mattis diam. Suspendisse blandit, odio a consequat blandit, ligula elit fermentum diam, eget rhoncus sem arcu elementum arcu. Proin ac dui sed arcu pretium volutpat. Nam condimentum enim eu sem finibus aliquam.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a efficitur massa. Donec mi ipsum, volutpat lobortis dapibus nec, tempus sed ante. Integer ut lacinia dui, in egestas nibh. Nunc at elit massa. Etiam aliquet viverra metus at sodales. Nulla fermentum interdum elit ut fermentum. Morbi volutpat turpis nunc, eu facilisis nisl volutpat vel. Duis id mattis diam. Suspendisse blandit, odio a consequat blandit, ligula elit fermentum diam, eget rhoncus sem arcu elementum arcu. Proin ac dui sed arcu pretium volutpat. Nam condimentum enim eu sem finibus aliquam.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a efficitur massa. Donec mi ipsum, volutpat lobortis dapibus nec, tempus sed ante. Integer ut lacinia dui, in egestas nibh. Nunc at elit massa. Etiam aliquet viverra metus at sodales. Nulla fermentum interdum elit ut fermentum. Morbi volutpat turpis nunc, eu facilisis nisl volutpat vel. Duis id mattis diam. Suspendisse blandit, odio a consequat blandit, ligula elit fermentum diam, eget rhoncus sem arcu elementum arcu. Proin ac dui sed arcu pretium volutpat. Nam condimentum enim eu sem finibus aliquam.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a efficitur massa. Donec mi ipsum, volutpat lobortis dapibus nec, tempus sed ante. Integer ut lacinia dui, in egestas nibh. Nunc at elit massa. Etiam aliquet viverra metus at sodales. Nulla fermentum interdum elit ut fermentum. Morbi volutpat turpis nunc, eu facilisis nisl volutpat vel. Duis id mattis diam. Suspendisse blandit, odio a consequat blandit, ligula elit fermentum diam, eget rhoncus sem arcu elementum arcu. Proin ac dui sed arcu pretium volutpat. Nam condimentum enim eu sem finibus aliquam.</p>
        <p id="parrafo">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a efficitur massa. Donec mi ipsum, volutpat lobortis dapibus nec, tempus sed ante. Integer ut lacinia dui, in egestas nibh. Nunc at elit massa. Etiam aliquet viverra metus at sodales. Nulla fermentum interdum elit ut fermentum. Morbi volutpat turpis nunc, eu facilisis nisl volutpat vel. Duis id mattis diam. Suspendisse blandit, odio a consequat blandit, ligula elit fermentum diam, eget rhoncus sem arcu elementum arcu. Proin ac dui sed arcu pretium volutpat. Nam condimentum enim eu sem finibus aliquam.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a efficitur massa. Donec mi ipsum, volutpat lobortis dapibus nec, tempus sed ante. Integer ut lacinia dui, in egestas nibh. Nunc at elit massa. Etiam aliquet viverra metus at sodales. Nulla fermentum interdum elit ut fermentum. Morbi volutpat turpis nunc, eu facilisis nisl volutpat vel. Duis id mattis diam. Suspendisse blandit, odio a consequat blandit, ligula elit fermentum diam, eget rhoncus sem arcu elementum arcu. Proin ac dui sed arcu pretium volutpat. Nam condimentum enim eu sem finibus aliquam.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a efficitur massa. Donec mi ipsum, volutpat lobortis dapibus nec, tempus sed ante. Integer ut lacinia dui, in egestas nibh. Nunc at elit massa. Etiam aliquet viverra metus at sodales. Nulla fermentum interdum elit ut fermentum. Morbi volutpat turpis nunc, eu facilisis nisl volutpat vel. Duis id mattis diam. Suspendisse blandit, odio a consequat blandit, ligula elit fermentum diam, eget rhoncus sem arcu elementum arcu. Proin ac dui sed arcu pretium volutpat. Nam condimentum enim eu sem finibus aliquam.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a efficitur massa. Donec mi ipsum, volutpat lobortis dapibus nec, tempus sed ante. Integer ut lacinia dui, in egestas nibh. Nunc at elit massa. Etiam aliquet viverra metus at sodales. Nulla fermentum interdum elit ut fermentum. Morbi volutpat turpis nunc, eu facilisis nisl volutpat vel. Duis id mattis diam. Suspendisse blandit, odio a consequat blandit, ligula elit fermentum diam, eget rhoncus sem arcu elementum arcu. Proin ac dui sed arcu pretium volutpat. Nam condimentum enim eu sem finibus aliquam.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a efficitur massa. Donec mi ipsum, volutpat lobortis dapibus nec, tempus sed ante. Integer ut lacinia dui, in egestas nibh. Nunc at elit massa. Etiam aliquet viverra metus at sodales. Nulla fermentum interdum elit ut fermentum. Morbi volutpat turpis nunc, eu facilisis nisl volutpat vel. Duis id mattis diam. Suspendisse blandit, odio a consequat blandit, ligula elit fermentum diam, eget rhoncus sem arcu elementum arcu. Proin ac dui sed arcu pretium volutpat. Nam condimentum enim eu sem finibus aliquam.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a efficitur massa. Donec mi ipsum, volutpat lobortis dapibus nec, tempus sed ante. Integer ut lacinia dui, in egestas nibh. Nunc at elit massa. Etiam aliquet viverra metus at sodales. Nulla fermentum interdum elit ut fermentum. Morbi volutpat turpis nunc, eu facilisis nisl volutpat vel. Duis id mattis diam. Suspendisse blandit, odio a consequat blandit, ligula elit fermentum diam, eget rhoncus sem arcu elementum arcu. Proin ac dui sed arcu pretium volutpat. Nam condimentum enim eu sem finibus aliquam.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a efficitur massa. Donec mi ipsum, volutpat lobortis dapibus nec, tempus sed ante. Integer ut lacinia dui, in egestas nibh. Nunc at elit massa. Etiam aliquet viverra metus at sodales. Nulla fermentum interdum elit ut fermentum. Morbi volutpat turpis nunc, eu facilisis nisl volutpat vel. Duis id mattis diam. Suspendisse blandit, odio a consequat blandit, ligula elit fermentum diam, eget rhoncus sem arcu elementum arcu. Proin ac dui sed arcu pretium volutpat. Nam condimentum enim eu sem finibus aliquam.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a efficitur massa. Donec mi ipsum, volutpat lobortis dapibus nec, tempus sed ante. Integer ut lacinia dui, in egestas nibh. Nunc at elit massa. Etiam aliquet viverra metus at sodales. Nulla fermentum interdum elit ut fermentum. Morbi volutpat turpis nunc, eu facilisis nisl volutpat vel. Duis id mattis diam. Suspendisse blandit, odio a consequat blandit, ligula elit fermentum diam, eget rhoncus sem arcu elementum arcu. Proin ac dui sed arcu pretium volutpat. Nam condimentum enim eu sem finibus aliquam.</p>
  </article>
</template>

<style>
  article {
    width: 1000px;
  }
  p {
    width: 400px;
  }
  #parrafo {
    color: red;
    font-weight: bold;
  }
</style>

